apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mangos_zero.fullname" . }}
  labels:
    {{- include "mangos_zero.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mangos_zero.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mangos_zero.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "mangos_zero.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: mangos-conf
        configMap:
          name: {{ include "mangos_zero.fullname" . }}-mangosd-conf
          items:
          - key: mangos.conf.dist
            path: mangos.conf.dist
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -c 
            - /etc/mangos/mangos.conf.dist
          ports:
            - name: game-server
              containerPort: 8085
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
          - mountPath: /etc/mangos/mangos.conf.dist
            name: mangos-conf
            subPath: mangos.conf.dist
          readinessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
