apiVersion: v1
kind: Service
metadata:
  name: {{ include "mangos_zero.fullname" . }}
  labels:
    {{- include "mangos_zero.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: game-server
      protocol: TCP
      name: game-server
  selector:
    {{- include "mangos_zero.mangosSelectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mangos_zero.fullname" . }}
  labels:
    {{- include "mangos_zero.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: realm-server
      protocol: TCP
      name: realm-server
  selector:
    {{- include "mangos_zero.realmdSelectorLabels" . | nindent 4 }}
